### ISSUE TITLE
<cstring> needed for memcpy() definition

### ISSUE THREAD

**Issue by taobrienlbl** [ClimateGlobalChange/tempestremap#1]
When compiling tempestgecore on edison, the compiler complains that memcpy is not defined for PolynomialInterp.cpp and FixedPoint.h.  Adding an include for cstring to the top of the files fixes this.  

Perhaps an #ifdef flag is needed to detect a particular compilation environment?

**Comment by paullric** [comment]
#include <cstring> has been added to these files
