### ISSUE TITLE
Cannot create variable "time"

### ISSUE THREAD

**Issue by brianpm** [ClimateGlobalChange/tempestremap#105]
I'm having a problem with remapping some files. After successfully following the instructions for some other data, this data source seems to be different, but I'm not seeing how. Here are the steps I'm doing:

- `GenerateRLLMesh --in_file_lat "lat" --in_file_lon "lon" --in_file ./MCD06COSP_M3_MODIS.A2002182.062.2022168173307.nc --file MCD06COSP_M3_MODIS.EXODUS.g`
- Similar command for a CESM FV09 grid
- `GenerateOverlapMesh --a MCD06COSP_M3_MODIS.EXODUS.g --b cesm_f09.EXODUS.g --out overlap_modis1deg_cesmf09.g`
- `GenerateOfflineMap --in_mesh MCD06COSP_M3_MODIS.EXODUS.g --out_mesh cesm_f09.EXODUS.g --ov_mesh overlap_modis1deg_cesmf09.g --in_np 1 --out_map mapping.nc`
- `ApplyOfflineMap --map mapping.nc --in_data MCD06COSP_M3_MODIS.A2002182.062.2022168173307.nc --out_data out.nc`

As far as I can tell, things are going fine until the last step, when I get an exception:
```
Parameters:
  --map <string> ["mapping.nc"]
  --in_data <string> ["MCD06COSP_M3_MODIS.A2002182.062.2022168173307.nc"]
  --out_data <string> ["out.nc"]
  --in_data_list <string> [""]
  --out_data_list <string> [""]
  --var <string> [""]
  --ncol_name <string> ["ncol"]
  --bounds <string> [""]
  --out_double <bool> [false]
  --preserve <string> [""]
  --preserveall <bool> [false]
  --fillvalue <double> [0.000000]
  --logdir <string> [""]
------------------------------------------------------------
Loading offline map.. Done
Processing "MCD06COSP_M3_MODIS.A2002182.062.2022168173307.nc"
..MODIS_CLD_HISTO
....EXCEPTION (src/NetCDFUtilities.cpp, Line 365) Cannot create variable "time"
------------------------------------------------------------
```

I'm guessing I've done something bad in my processing that makes this MODIS file, but I have not been able to figure out what it would be. Here's an ncdump of that file:

```
netcdf MCD06COSP_M3_MODIS.A2002182.062.2022168173307 {
dimensions:
        COT = 7 ;
        PRES = 7 ;
        lat = 180 ;
        lon = 360 ;
        time = 1 ;
        nbnd = 2 ;
variables:
        double COT(COT) ;
        double PRES(PRES) ;
        double lat(lat) ;
                lat:units = "degrees_north" ;
        double lon(lon) ;
                lon:units = "degrees_east" ;
        int64 time(time) ;
                time:units = "days since 2002-07-16 11:59:59.500000" ;
                time:calendar = "proleptic_gregorian" ;
        double MODIS_CLD_HISTO(time, COT, PRES, lat, lon) ;
                MODIS_CLD_HISTO:_FillValue = 9.96920996838687e+36 ;
                MODIS_CLD_HISTO:title = "Cloud_Optical_Thickness_Total: JHisto_vs_Cloud_Top_Pressure" ;
                MODIS_CLD_HISTO:JHisto_Bin_Boundaries = 0., 0.3, 1.3, 3.6, 9.4, 23., 60., 150. ;
                MODIS_CLD_HISTO:JHisto_Bin_Boundaries_Joint_Parameter = 0., 180., 310., 440., 560., 680., 800., 1100. ;
        byte cloud_mask(time, lat, lon) ;
                cloud_mask:dtype = "bool" ;
        double CLDTOT_MODIS(time, lat, lon) ;
                CLDTOT_MODIS:_FillValue = 9.96920996838687e+36 ;
        double CLDTHCK_MODIS(time, lat, lon) ;
                CLDTHCK_MODIS:_FillValue = 9.96920996838687e+36 ;
                CLDTHCK_MODIS:Description = "High-topped (pres < 440hPa), thick (tau > 23) cloud fraction." ;
        int64 nbnd(nbnd) ;
        int64 time_bnds(time, nbnd) ;
                time_bnds:units = "seconds since 2002-07-01 00:00:00" ;
                time_bnds:calendar = "proleptic_gregorian" ;
}
```

Any idea what might be going on?
BTW, I'm running this on an Apple M1-based laptop and TempestRemapped was installed via conda.

**Comment by mt5555** [comment]
To apply an offline map, try NCO's ncremap.  It's very robust w.r.t. to preserving metadata and handling non-remapped variables.

**Comment by brianpm** [comment]
Thanks, Mark. I'll try ncremap. I was trying to stick with all tempestremap stuff because NCO isn't building correctly on M1 Macs (well, ESMF isn't building, I think is the actual problem).
