### ISSUE TITLE
RLL longitude interface problem?

### ISSUE THREAD

**Issue by czender** [ClimateGlobalChange/tempestremap#15]
Hi Tempestuous ones,

I used Tempest to create RLL mapping files like 1x1<->2x2 degree, then I distributed these mapfiles to a few users who later notified me that they could not plot the resultant regriddings. It turns out that the Tempest longitude interfaces (but not the latitude interfaces) look bad. 

I constructed the Tempest RLL mapfile with:
GenerateRLLMesh --lat 180 --lon 360 --file ${DATA}/rgr/msh_180x360.g
GenerateRLLMesh --lat 90 --lon 180 --file ${DATA}/rgr/msh_90x180.g
GenerateOverlapMesh --a ${DATA}/rgr/msh_180x360.g --b ${DATA}/rgr/msh_90x180.g --out ${DATA}/rgr/msh_ovr_180x360_to_90x180.g # works
GenerateOfflineMap --in_mesh ${DATA}/rgr/msh_180x360.g --out_mesh ${DATA}/rgr/msh_90x180.g --ov_mesh ${DATA}/rgr/msh_ovr_180x360_to_90x180.g --out_map ${DATA}/maps/map_180x360_to_90x180.20150818.nc

This produces these interfaces:
zender@roulee:/data/zender/grids$ ncks -H -v xv_a map_180x360_to_90x180.20150818.nc | /bin/more
n_a[0] nv_a[0] xv_a[0]=0 
n_a[0] nv_a[1] xv_a[1]=1 
n_a[0] nv_a[2] xv_a[2]=0 
n_a[0] nv_a[3] xv_a[3]=0 
...

Tempest puts three zero-longitude interfaces around the first gridcell where there should only be two. I verified this by constructing the same grid (in SCRIP format) using the new SCRIP-grid-generation feature of NCO (present since version 4.5.2-alpha7):
zender@roulee:/data/zender/grids$ ncks -O -D 1 --rgr grd_ttl='Offset grid 180x360' --rgr grid=${DATA}/grids/180x360_SCRIP.20150820.nc --rgr lat_nbr=180 --rgr lon_nbr=360 --rgr lat_typ=ngl_eqi_fst --rgr lon_typ=Grn_wst ~/nco/data/in.nc ~/foo.nc
zender@roulee:/data/zender/grids$ ncks -H -v grid_corner_lon ${DATA}/grids/180x360_SCRIP.20150820.nc | /bin/more
grid_size[0] grid_corners[0] grid_corner_lon[0]=0 
grid_size[0] grid_corners[1] grid_corner_lon[1]=1 
grid_size[0] grid_corners[2] grid_corner_lon[2]=1 
grid_size[0] grid_corners[3] grid_corner_lon[3]=0
...

Running the NCO-generated grid through ESMF_RegridWeightGen produces the expected results and correct interface longitudes. So it looks like a Tempest bug in the longitude interfaces for RLL grids.

Best,
c

**Comment by mt5555** [comment]
I've also been trying to use TempestRemap files on lat/lon grids.  A few comments:  

You can also run GenerateOfflineMap with the SCRIP files produced by ncks.  It can read either .g or SCRIP format.  That what I've been doing, since I wanted CAM-FV style grids with cell centers at the poles that ncks can produce.   

For high-res lat/lon grids,  GenerateOfflineMap sometimes leaves some holes in the target grid, which can be fixed if you use the older version to make the overlap grid, GenerateOverlapMesh_v1.     

GenerateOfflineMap doesn't have (yet?) have the polar "fixes" that ESMF has though (I think it averaging all the pole values, since they should actually all have the same value).

**Comment by czender** [comment]
Ahh. You point out that GenerateOfflineMap works with SCRIP grids, which I didn't know. Thanks. Does this mean that GenerateOverlapMesh also accepts SCRIP grids?

**Comment by mt5555** [comment]
yep

**Comment by paullric** [comment]
Yes there is a SCRIP grid reader accessible by all mesh I/O routines but no writer (yet).

~ Paul

**Comment by paullric** [comment]
Hi Charlie,

The issue seems to be that Tempest always treats the pole points as having zero longitude (since it tries to maintain a bijective map between RLL space and XYZ, typically not possible at the poles).  I'll have a look at putting in a fix for this issue for rectilinear grids.

~ Paul

**Comment by paullric** [comment]
I’ve pushed out a fix that should correct the longitudinal coordinates of polar nodes.  Please verify.

~ Paul

**Comment by czender** [comment]
Would you please port this into next-gen? I can only handle keeping up-to-date with one branch and I migrated to next-gen a few weeks back.

**Comment by paullric** [comment]
Hi Charlie,

Next-gen was merged into master last week, so it is now deprecated.

~ Paul

**Comment by czender** [comment]
The fix works for me, thanks.
