### ISSUE TITLE
Tempest emits return code = 0 for (some) failed executions

### ISSUE THREAD

**Issue by czender** [ClimateGlobalChange/tempestremap#19]
The return code seen by the calling shell should be zero only if the command executed without a fatal error. ncremap want to use this return code to diagnose failures of GenerateOverlapMesh and GenerateOfflineMap. For now ncremap works around this issue by removing any mesh/map files prior to calling the tempest utilities and then checking for the presence of the files after executing the utilities. Absence means the tempest utilities failed, but a trustworthy return code would be more robust.

**Comment by paullric** [comment]
This should be fixed in the latest push.  Please verify and close if
satisfactorily resolved.

**Comment by czender** [comment]
Seems OK now. Thanks!
