### ISSUE TITLE
Inverse Map out of range -> VR SE to regional RLL

### ISSUE THREAD

**Issue by zarzycki** [ClimateGlobalChange/tempestremap#21]
When remapping a refined SE grid to a regional LL grid, this error arises sometimes...

..Element 51100
..Element 51200
..EXCEPTION (LinearRemapSE0.cpp, Line 898) Inverse Map out of range (1.00000e+00 5.11226e-01)

One way around this seems to be slightly perturbing the resolution of the regional LL grid (i.e., from 7 km to 6km or 10km). Of note, the error always occurs at the same Element #, so assume it's propagating from the base SE grid.

**Comment by paullric** [comment]
Fixed through better error reporting.
