### ISSUE TITLE
GenerateOverlapMesh automatically warn if grid_a is larger than grid_b

### ISSUE THREAD

**Issue by mt5555** [ClimateGlobalChange/tempestremap#29]
relaying suggestion from C. Zender.  

How about having GenerateOverlapMesh check if sum(area_a) >> sum(area_b) and then exit with an error message unless the user specified some flag, like --force-mesh-order.

This will make the process of generation atmosphere <-> ocean maps more robust, as right now it is up to the user to know that the ocean should be grid a, while the atmosphere should be grid b.

**Comment by paullric** [comment]
This has been fixed with override flag "--allow_no_overlap".  Default behavior is now to disallow the result if an element on mesh A is found which does not appear to overlap any element on mesh B.
