### ISSUE TITLE
Lat/Lon preservation

### ISSUE THREAD

**Issue by arhoades** [ClimateGlobalChange/tempestremap#3]
I've noticed that after using tempestremap to regrid Spectral-Element CESM output variables the lat/lon properties aren't maintained in the netCDF file. This creates a consistency issue when using NCL (since it is "fussy" with lat/lon properties for variables - https://www.ncl.ucar.edu/Document/Graphics/error_msg.shtml).  

In order to get around this issue, I currently use the NCL function fspan to create an artificial lat/lon (based on the lat_begin, lon_begin, lat_end, lon_end, and distance between, during the tempestremap process) and assign it to the given variable.

**Comment by paullric** [comment]
- Added some hacky lat/lon variable retention to latest version of code
