### ISSUE TITLE
Tempest2 produces unexpected map compared to Tempest1 

### ISSUE THREAD

**Issue by czender** [ClimateGlobalChange/tempestremap#34]
Tempest gurus (and fyi to @mt5555),

I just built the latest (today's) snapshot of TempestRemap.
This is my first time using Tempest 2.0.
The Linux build went smoothly.
(I can't yet get Mac build to complete, but that's a separate issue).
On Linux the commands below that worked as I have come to expect with 
Tempest1 now behave very differently with Tempest2.
The generated mapfile converts the 1D CAM-SE input to 1D (SE?) output
rather than 2D RLL as I expected.
(The input files are in the ACME map/grid repository and can be supplied upon request, though the issue seems to be generic and not specific to these grids).
This seems to indicated a default setting has changed within Tempest.
At the least, this breaks back-compatibility between Tempest2 and
Tempest1, and results in headaches for ncremap users of Tempest.

1. Is this a Tempest2 bug or a feature?
2. How do I recover the expected Tempest1 functionality with Tempest2? i.e., do I need to set options differently?

```
zender@skyglow:~$ GenerateOverlapMesh --a ${DATA}/grids/ne30np4_pentagons.091226.nc --b ${DATA}/grids/129x256_SCRIP.20150901.nc --out ~/msh_ovr.g
zender@skyglow:~$ GenerateOfflineMap --in_mesh ${DATA}/grids/ne30np4_pentagons.091226.nc --out_mesh ${DATA}/grids/129x256_SCRIP.20150901.nc --ov_mesh ~/msh_ovr.g --out_map ~/map.nc
zender@skyglow:~$ ncks -v dst_grid_dims ~/map.nc
netcdf map {
  dimensions:
    dst_grid_rank = 1 ;

  variables:
    int dst_grid_dims(dst_grid_rank) ;
      dst_grid_dims:name0 = "num_dof" ;

  data:
    dst_grid_dims = 33024 ; 

} // group /

```

**Comment by paullric** [comment]
Hmm seems like a bug due to lack of an effective regression test suite.  Can you point me at 129x256_SCRIP.20150901.nc?

~ Paul

**Comment by czender** [comment]
http://dust.ess.uci.edu/tmp/129x256_SCRIP.20150901.nc

**Comment by paullric** [comment]
Ok should be fixed now.  There was some remnant code from the MOAB integration that caused the dimension information to be overwritten after it was initialized.

~ Paul

**Comment by czender** [comment]
Works for me too. Thanks!
