### ISSUE TITLE
SCRIP format standards

### ISSUE THREAD

**Issue by hmb1** [ClimateGlobalChange/tempestremap#40]
Hi There,
I have some SCRIP NetCDF files to process and I am wondering what the standards are with respect to the polar regions and wrapping ( grid cells that span the Greenwich meridian or the Date line)

The SCRIP file I have has some polar cells that are very wide in longitude (>100 degrees) and very narrow in latitude. ( < 0.5 degrees). It also has some cells that cross the Greenwich meridian ( longitude goes from ( 359.7505422628756833 - 0.2494577371223946 ).

I need an unambiguous way to differenciate between these two cell types.
Is this something that you have come across before ?
Are wrapped cells even legal in SCRIP ?
Any help greatly appreciated.
Thanks

...Henry

**Comment by paullric** [comment]
It's my understanding that SCRIP is ambivalent to whether the grid cells actually wrap.  Essentially TempestRemap immediately converts the lat/lon coords from the SCRIP file to XYZ coordinates on load, so it has no notion about what is a polar cell and what is not.

I'm not exactly sure I've answered your question, however.
