### ISSUE TITLE
frac_a and frac_b are not calculated corrected

### ISSUE THREAD

**Issue by brhillman** [ClimateGlobalChange/tempestremap#42]
It appears as though `frac_a` and `frac_b` in output mapping files are not being calculated correctly, and rather output as all 1s. Comparing ESMF area-averaged to Tempest conservative (monotr) mapping files for an example case mapping between a ne4 and oQU240 mpas grid:

![oqu240_to_ne4](https://user-images.githubusercontent.com/15826727/49322111-1a2fb600-f4c1-11e8-8a76-3b35887166ed.png)

`frac_a` is all 1s for both ESMF and Tempest in this case, but this is probably not guaranteed to be the case.

**Comment by paullric** [comment]
This should now be fixed in commit dd050751c14976cb360e38ccd79f8135412ea716.
