### ISSUE TITLE
Masks from source and target grids are not propagated

### ISSUE THREAD

**Issue by brhillman** [ClimateGlobalChange/tempestremap#44]
When working with SCRIP-format source or target grids, the mask variables are not propagated through to the output mapping files. This is problematic for cases where either the source or target grid is a regular global grid, on which a model component (i.e., land or ocean) may be partially masked (inactive). For example, for a finite-volume global ocean grid, the mask should determine where there is ocean (mask = 1) or not (mask = 0). Older SCRIP files contain this information, but if this mask is not propagated through to the output mapping files, this information is lost and cannot be used by other tools without a bit of trickery to copy data from the original SCRIP files. This feature is critical to using Tempest Remap in E3SM, for example, because generation of domain files (which describe the fraction of one model component on the grid of another) need the mask to determine fractional coverage of the component.

**Comment by paullric** [comment]
The grid variable you would like to propagate from the SCRIP file is "grid_imask", correct?  And this should be propagated to mask_a and mask_b variables in the output map?

**Comment by brhillman** [comment]
Yes that sounds right. Thanks!

**Comment by paullric** [comment]
This should now be functional in commit 99c9bbdc07804dce0b4221173cd9b25105c5c0e9.  Please verify.

**Comment by brhillman** [comment]
Yes this seems to be fixed in https://github.com/ClimateGlobalChange/tempestremap/commit/99c9bbdc07804dce0b4221173cd9b25105c5c0e9.
