### ISSUE TITLE
Preservation of variables without horizontal dependence

### ISSUE THREAD

**Issue by zarzycki** [ClimateGlobalChange/tempestremap#5]
If easy, bringing variables such as P0 (scalar) and hyai, hybi, (1D) etc. (used in converting between hybrid -> pressure coords) from source to destination file in ApplyOfflineMap would be nice. Also the lev coordinate.

Currently a hacked solution is to have an NCL script that does this after the remap process.

**Comment by paullric** [comment]
Preservation is now supported via --preserveall and --preserve command line arguments.  However, this still needs further testing; please test, if successful will close this ticket.
