### ISSUE TITLE
bad weights,  ne30->ne256 map

### ISSUE THREAD

**Issue by mt5555** [ClimateGlobalChange/tempestremap#59]
Bad map file, using the latest TR, to make a ne30 -> ne256 map . (using ne30 and ne256 exodus files generated by TR):

set exepath = ~/codes/tempestremap

set NE=30
set NE2=256

set echo
echo "CS Mesh"
set atmgrid = TEMPEST_NE${NE}.g
$exepath/GenerateCSMesh --alt --res $NE --out_format Netcdf4 --file $atmgrid
if ( $status ) exit

set atmgrid2 = TEMPEST_NE${NE2}.g
$exepath/GenerateCSMesh --alt --res $NE2 --out_format Netcdf4 --file $atmgrid2
if ( $status ) exit

echo "OVERLAP mesh"
rm -f overlap_mesh.log
$exepath/GenerateOverlapMesh --b $atmgrid --a $atmgrid2 --out overlap_mesh.g  >& overlap_mesh.log
if ( $status ) exit

echo "mono map"
rm -f map1.out
set mapname = map_ne${NE}np4_to_ne${NE2}np4_mono.nc
$exepath/GenerateOfflineMap --in_mesh $atmgrid  --out_mesh $atmgrid2 \
  --ov_mesh overlap_mesh.g   --in_type cgll --in_np 4 --out_type cgll --out_np 4 \
  --out_double --out_format Netcdf4 \
  --mono  --out_map $mapname   >&  map1.out

...

Analyzing map
..Per-dof consistency  (tol 1.00000e-08).. PASS
..Per-dof conservation (tol 1.00000e-08).. PASS
..Per-dof monotonicity (tol 1.00000e-12).. PASS
..
..  Total nonzero entries: 69932378
..   Column index min/max: 1 / 48602 (48602 source dofs)
..      Row index min/max: 1 / 3538946 (3538946 target dofs)
..      Source area / 4pi: 9.999999999693960e-01
..    Source area min/max: 4.244854494004986e-05 / 4.759525090013127e-04
..      Target area / 4pi: 1.000000000000005e+00
..    Target area min/max: 6.013376296320897e-07 / 6.536378323193907e-06
..    Map weights min/max: nan / nan
..       Row sums min/max: nan / nan
..   Consist. err min/max: nan / nan
..    Col wt.sums min/max: nan / nan
..   Conserv. err min/max: nan / nan
..    Global conserv. err: nan
..
..Histogram of nonzero entries in sparse matrix
....Column 1: Number of nonzero entries (bin minimum)
....Column 2: Number of columns with that many nonzero values
....Column 3: Number of rows with that many nonzero values
..[[16, 0, 2566296],[28, 0, 894672],[31, 48602, 77978]]
..
..Histogram of weights
....Column 1: Lower bound on weights
....Column 2: Upper bound on weights
....Column 3: # of weights in that bin
..[[10, inf, 69932378]]
..
..NOTE: Source weights do not agree with sphere area (tol 1.00000e-12)

**Comment by paullric** [comment]
Added a possible fix in commit b936c94

**Comment by mt5555** [comment]
fixed.
