### ISSUE TITLE
Option to regrid all non 1-D/scalar variables in a file

### ISSUE THREAD

**Issue by zarzycki** [ClimateGlobalChange/tempestremap#6]
Might be nice to add a flag that pulls varlist from .nc file, and regrids all vars which are not 1-D or scalars. This would be helpful for files with many variables.

**Comment by mt5555** [comment]
For CAM output:  one could regrid all variables with a "ncol" dimension.

And what about automatic detection of vectors?   Or perhaps a way to specify variables that are vector components, so they can treated properly.  (e.g. convert to cartesian, remap, convert back)

**Comment by paullric** [comment]
All variables with "ncol" dimension or "lat/lon" dimension are now detected when --var is not specified on the command line.

Automatic detection of vectors is an issue.  And correct treatment of vectors requires a global Poisson solve in order to convert from vorticity and divergence back to velocity.

**Comment by zarzycki** [comment]
Minor issue here. With CAM-SE data and --var not specified (forcing all regrid), lat(ncol) and lon(ncol) are also included/regridded. This breaks my offline code to add lat/lon dimensionality to the regridded file (because lat/lon already exist as variables). Since ncks doesn't like stripping vars named after dimensions, I currently rename lat/lon using ncrename which is a bit of a hacked solution to a hacked solution.

Not specifying --var seems to do the ticket for most things, so possibly just always exclude lat and lon from being "regridded"? Honestly, I can't really think of physically why you'd want to regrid another grid's lat/lon arrays outside of maybe looking at regridding error?

**Comment by mt5555** [comment]
Other regridders also skip  'gw' and 'area' - and instead replace them with the correct weights from the mapping file.

**Comment by czender** [comment]
@zarzycki ncks can now apply Tempest mapfiles directly. It adds some useful metadata (including gw and area) that may obviate the need to strip the remapped file.
