### ISSUE TITLE
`--alt` flag was removed but still mentioned in README and used in one test

### ISSUE THREAD

**Issue by xylar** [ClimateGlobalChange/tempestremap#61]
`--alt` was removed here:
https://github.com/ClimateGlobalChange/tempestremap/commit/9e82453059cb1aee0ea1373a59eb1d1fbe605f1c
but is still used here:
https://github.com/ClimateGlobalChange/tempestremap/blob/91e19894843da881ed882a09c326a22d39835f16/test/run.sh#L3
and here:
https://github.com/ClimateGlobalChange/tempestremap/blame/1550afdf42e7ad21f45c122a327a8617e71eb193/README.md#L90

(I noticed this in the process of doing a [trial build](https://github.com/conda-forge/tempest-remap-feedstock/pull/13) for conda-forge.)

**Comment by paullric** [comment]
Discussed with @mt5555 and decided to add "--alt" back in as a non-functional command line option.  Fixed in commit 64a8d10.
