### ISSUE TITLE
Request for a release candidate

### ISSUE THREAD

**Issue by xylar** [ClimateGlobalChange/tempestremap#63]
I'd like to request a release candidate sometime before the next release so I can test on conda-forge.  I have tested with master in the past (successfully), see https://github.com/conda-forge/tempest-remap-feedstock/pull/13.

This would be very helpful for testing MOAB and mptempest as well, see https://github.com/conda-forge/moab-feedstock/pull/29 and (to be added shortly).

**Comment by paullric** [comment]
Realized I'd filed this request under "read" without actually doing it.
Since I haven't had many complaints recently about bugs or other issues,
I've now released v2.0.4.

https://github.com/ClimateGlobalChange/tempestremap/releases/tag/v2.0.4

~ Paul

**Comment by xylar** [comment]
No worries.  I mainly wanted a release candidate so I could test Moab's `master` with it.  But I can also do that with a release.  It's just more bother for you if I find problems ;-)
