### ISSUE TITLE
Erroneous behavior with intel compilers on edison@NERSC

### ISSUE THREAD

**Issue by taobrienlbl** [ClimateGlobalChange/tempestremap#8]
Compiling tempestremap using the Intel compiler set on Edison at NERSC results in a slew of inconsistency warnings when creating a weight file.  The resulting weight file ends up with Infinities interlaced throughout, and subsequent regridding operations using the weight file results in clearly erroneous interpolation.

Recompiling with the GNU compiler set and re-running identical steps results in the creation of a weight file without Infinities, and subsequent regridding operations appear to be correct.

A sample script, which produces different weight files depending on the compiler set, follows:

``` bash
./GenerateCSMesh --res 16 --file tempestremap-ne16np4-mesh.g
./GenerateRLLMesh  --lon 180 --lat 90 --lat_begin -89.0 --lon_begin 1.0 --lat_end 89.0 --lon_end 359.0 --file tempestremap-latlon-2.0-degree-mesh.g
./GenerateOverlapMesh --a tempestremap-latlon-2.0-degree-mesh.g --b tempestremap-ne16np4-mesh.g --out tempestremap-latlon-2.0-degree_ne16np4_overlap.g
./GenerateOfflineMap --in_mesh tempestremap-ne16np4-mesh.g --out_mesh tempestremap-latlon-2.0-degree-mesh.g --ov_mesh tempestremap-latlon-2.0-degree_ne16np4_overlap.g --in_type cgll --out_type fv --out_map tempestremap_ne16np4_latlon-2.0-degree_weights.nc
```

It appears that the overlap files differ (even in size), so it seems the issue may occur at/before the `GenerateOverlapMesh` stage.
## Build Details

For the Intel compiler build, I first loaded the following modules:

``` bash
module load cray-netcdf/4.3.2
module load netcdf-cxx/4.2
```

For the GNU compiler build, I additionally swapped the programming environment:

``` bash
module swap PrgEnv-intel PrgEnv-gnu
module load cray-netcdf/4.3.2
module load netcdf-cxx/4.2
```

The following diff file (relative to commit 32f939ec294016d7003d7533cf683261893c2801) shows the modifications I made to `Makefile` to compile at NERSC. 

``` Diff
diff --git a/Makefile b/Makefile
index 1abfa2d..7594967 100644
--- a/Makefile
+++ b/Makefile
@@ -1,16 +1,16 @@
 ##############################################################################
 # Compiler and flags
-CC= g++
-CFLAGS= -O3
+CC= CC
+CFLAGS= -O3 -std=c++11

 USEBLAS= True

 # NETCDF library directories
-NETCDF_INCLUDEDIR=/opt/local/include
-NETCDF_LIBDIR=/opt/local/lib
+NETCDF_INCLUDEDIR=/usr/common/graphics/netcdf-cxx/4.2/include
+NETCDF_LIBDIR=/usr/common/graphics/netcdf-cxx/4.2/lib

 # Library files to include
-LDFILES= -lnetcdf -lnetcdf_c++ -framework accelerate
+LDFILES=-lnetcdf_c++

 ##############################################################################
 # DO NOT MODIFY BELOW THIS LINE
```

**Comment by HarinarayanKrishnan** [comment]
I noticed this as well.

I am not sure if you are aware of this, but "module load cascade" now
provides the executables from tempestremap in the execution path. Feel free
to use it if you like, it was built with gcc.

**Comment by taobrienlbl** [comment]
Thanks Hari--now that I know, I'll use the CASCADE one.

On Thu, Apr 2, 2015 at 1:58 PM, HarinarayanKrishnan <
notifications@github.com> wrote:

> I noticed this as well.
>
> I am not sure if you are aware of this, but "module load cascade" now
> provides the executables from tempestremap in the execution path. Feel free
> to use it if you like, it was built with gcc.
>
>
>
>
> On Thu, Apr 2, 2015 at 1:30 PM, taobrienlbl <notifications@github.com>
> wrote:
>
> > Compiling tempestremap using the Intel compiler set on Edison at NERSC
> > results in a slew of inconsistency warnings when creating a weight file.
> > The resulting weight file ends up with Infinities interlaced throughout,
> > and subsequent regridding operations using the weight file results in
> > clearly erroneous interpolation.
> >
> > Recompiling with the GNU compiler set and re-running identical steps
> > results in the creation of a weight file without Infinities, and
> subsequent
> > regridding operations appear to be correct.
> >
> > A sample script, which produces different weight files depending on the
> > compiler set, follows:
> >
> > ./GenerateCSMesh --res 16 --file tempestremap-ne16np4-mesh.g
> > ./GenerateRLLMesh --lon 180 --lat 90 --lat_begin -89.0 --lon_begin 1.0
> --lat_end 89.0 --lon_end 359.0 --file tempestremap-latlon-2.0-degree-mesh.g
> > ./GenerateOverlapMesh --a tempestremap-latlon-2.0-degree-mesh.g --b
> tempestremap-ne16np4-mesh.g --out
> tempestremap-latlon-2.0-degree_ne16np4_overlap.g
> > ./GenerateOfflineMap --in_mesh tempestremap-ne16np4-mesh.g --out_mesh
> tempestremap-latlon-2.0-degree-mesh.g --ov_mesh
> tempestremap-latlon-2.0-degree_ne16np4_overlap.g --in_type cgll --out_type
> fv --out_map tempestremap_ne16np4_latlon-2.0-degree_weights.nc
> >
> > It appears that the overlap files differ (even in size), so it seems the
> > issue may occur at/before the GenerateOverlapMesh stage.
> > Build Details
> >
> > For the Intel compiler build, I first loaded the following modules:
> >
> > module load cray-netcdf/4.3.2
> > module load netcdf-cxx/4.2
> >
> > For the GNU compiler build, I additionally swapped the programming
> > environment:
> >
> > module swap PrgEnv-intel PrgEnv-gnu
> > module load cray-netcdf/4.3.2
> > module load netcdf-cxx/4.2
> >
> > The following diff file (relative to commit 32f939e
> > <
> https://github.com/ClimateGlobalChange/tempestremap/commit/32f939ec294016d7003d7533cf683261893c2801
> >)
> > shows the modifications I made to Makefile to compile at NERSC.
> >
> > diff --git a/Makefile b/Makefile
> > index 1abfa2d..7594967 100644--- a/Makefile+++ b/Makefile@@ -1,16 +1,16
> @@
> >
> ##############################################################################
> > # Compiler and flags-CC= g++-CFLAGS= -O3+CC= CC+CFLAGS= -O3 -std=c++11
> >
> > USEBLAS= True
> >
> > # NETCDF library
> directories-NETCDF_INCLUDEDIR=/opt/local/include-NETCDF_LIBDIR=/opt/local/lib+NETCDF_INCLUDEDIR=/usr/common/graphics/netcdf-cxx/4.2/include+NETCDF_LIBDIR=/usr/common/graphics/netcdf-cxx/4.2/lib
> >
> > # Library files to include-LDFILES= -lnetcdf -lnetcdf_c++ -framework
> accelerate+LDFILES=-lnetcdf_c++
> >
> >
> ##############################################################################
> > # DO NOT MODIFY BELOW THIS LINE
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ClimateGlobalChange/tempestremap/issues/8>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ClimateGlobalChange/tempestremap/issues/8#issuecomment-89042848>
> .
>



-- 
Travis O'Brien
Research Scientist, Earth Sciences Division
Lawrence Berkeley National Lab
http://esd.lbl.gov/about/staff/travisobrien/
<http://esd.lbl.gov/about/staff/travisobrien/index.html>
(510) 495-8047
